environment:
    rewards:
        death:            -10
        apple:            1
        timestep:         0
        towards_apple:    0
        away_from_apple:  0

    vision:
        type:        "binary"
        directions:  8

    grid_size:  6
    initial_snake:  [[2, 1], [1, 1], [0, 1]]


mode:
    train:       false
    agent_play:  true
    teach:       false

    # Just in case you want to play snake
    user_play:   false


window:
    # Will visually display the environment if true
    active:  false
    size:    400
    title:   "Snek"

    vision_lines_active:  false

    colours:
        grid:
            - [34, 48, 66]
            - [21, 32, 46]

        snake:         [255, 255, 255]
        apple:         [255, 0, 0]
        vision_lines:  [0, 255, 0]


misc:
    debug:  false
